#!/usr/bin/env python3
import numpy
import case

class GridV2():
    def __init__(self):
        grid = numpy.array([[case.Case(0,i,j) for j in range(9)] for i in range(9)], dtype=object)
        self.grid = grid

    def g_print(self):
        print(self.grid)

    def case_val(self, x, y):
        case = self.grid[x][y]
        return case.get_val()
    #EN COURS
    def set_case(self, num, x ,y):
        return
